//texto 1 
console.log("Seja bem vindo bravo herói, meu nome é Ephrata sou o Espiríto Guia deste lugar e meu objetivo é ajudar os novos heróis a trilharem sua jornada. Essa é a parte preparatória para a sua batalha, vamos ver se você será capaz e se terá forças para sobreviver ou pelo menos pederemos criar um pouco de esperança... Enfim, tudo aqui começa e acaba em números, então espero que tenha SORTE, porque sua vida depende disso...")
//text 2
console.log("Agora os dados mágicos serão rodados duas vezez e irá nos dizer qual será sua arma e não somente isso, mas o nível dela e a soma desses dois valores será creditado em no XP do herói. Em seguida temos três Grandiozas Batalhas pela frente e os dados dirão se chegaremos ao final, ou se pelo menos sairemos vivos da primeira... Quer dizer... se você sairá... ")
//text 3
console.log("Chegamos...Que foi? O que você esperava? Escuridão e trevas ficam para heróis mais bem capacitados...Desculpe se não era o que esperava, vamos logo ao que interessa. Essa é a Floresta do Gancho, alguns parasitas um tanto quanto ferozes destroem tudo que veem e matam tudo que passa pelo caminho. Entretanto, essa Floresta é povoada por criaturas mágicas raras, a sobrevivência dessas especies corre um perigo eminente. O plano é o seguinte, vamos esperar!... Não acha um bom plano? Então deve ter um melhor ...Como imaginava...Continuando de onde parei, como o paradeiro desses predadores é um mistério, e sabemos que atacam ao calar da noite, aguardamos escurecer e libertaremos a Floresta.")
// text 4
console.log("A batalha será duvidida em turnos, se alcaçar bons números o máximos de dano será inflingido ao openente, a combinação de dados determinam o tempo da batalha e se o herói salvara a vida dos que veio proteger. Ao final de cada fase, os dados serão rodados novamente, indicando qual artefato mágico o herói ganhará para seguir a próxima batalha, como as armas, os artefatos também possui níveis e cada batalha te reserva um artefato mágico diferente, eles te concederão mais XP e forças para continuar. O que acontece se não conseguir muito XP? Bom, digamos que logo você saberá, mas basta dizer que se não houver forças suficientes para derrotar seus oponentes, só existe um caminho e digamos que se isso acontecer, não será possível continuar. Venha, já está escurecendo, falta pouco...   ")
// text 5
console.log("Consegue ver aquela pequena vila de Sátiros? Não são muitos, a maioria deles fugiram, apenas permanecem aqui aqueles que defendem a terra que nasceram, muitos estão preparados para se defender, mas não tantos estão preparados suficiente para sobreviver. Aqui começa sua primeira missão, vamos para perto, a lua está chegando ao ápice e precisamos ficar bem escondidos, digamos que sátiros não são seres de muita simpatia. Estão vindo do leste, vamos mais rápido, precisamos estar preparados. Sim, isso mesmo, são cinco lobos branco das montanhas. Mais rápido, eles estão sedentos pelo sangue das criaturas mágicas, eles são rápidos e forte então não vai ser um oponente fácil.") // você se põe em prontidão em frente aos sátiros, para defende-los, todos estão com suas devidas armaduras e espatas mal forjadas.


